version: "3.1"
services:

  bot:
   image: 270051160229.dkr.ecr.us-east-1.amazonaws.com/tt-bot
   ports:
     - "9001:8443"
#   volumes:
#     - ./bot:/home/ds/notebooks
   command: /opt/ds/bin/python -u /home/ds/notebooks/bot.py
   depends_on:
     - mongo
   environment:
     VIRTUAL_HOST: tt.mgcoders.com
     VIRTUAL_PORT: 8443
     LETSENCRYPT_HOST: tt.mgcoders.com
     LETSENCRYPT_EMAIL: info@mgcoders.com


  mongo:
    image: tutum/mongodb:3.2
    environment:
      AUTH: "no"


networks:
  default:
    external:
      name: nginx-proxy
