jupyter:
  build: .
  ports:
    - "0.0.0.0:8888:8888"
    - "0.0.0.0:6006:6006"
  volumes:
    - ./:/home/ds/notebooks
    - ./jupyter:/home/ds/.jupyter
  links:
    - mongo


mongo:
  image: tutum/mongodb:3.2
  environment:
    - AUTH="no"
