version: "3.1"
services:

  bot:
   build: .
   ports:
     - "9001:8443"
   command: /opt/ds/bin/python -u /home/ds/notebooks/bot.py
   volumes:
     - ./bot:/home/ds/notebooks
   depends_on:
     - mongo
   environment:
     VIRTUAL_HOST: tt.mgcoders.com
     VIRTUAL_PORT: 8443
     LETSENCRYPT_HOST: tt.mgcoders.com
     LETSENCRYPT_EMAIL: info@mgcoders.com
     TOKEN: ${TELEGRAM_TOKEN}
     MONGO: mongodb://mongo:27017/ttbot
     MODE: polling


  mongo:
    image: tutum/mongodb:3.2
    environment:
      AUTH: "no"


networks:
  default:
    external:
      name: nginx-proxy
